apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "hello-world.name" . }}-ingress"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ include "hello-world.name" . }}-service"
              port:
                number: {{ .Values.service.port }}
        - path: /v2
          pathType: Prefix
          backend:
            service:
              name: "{{ include "hello-world.name" . }}-service"
              port:
                number: 6969
        